# Generated by Django 4.0.5 on 2022-07-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_musician', models.CharField(max_length=200)),
                ('name_of_band', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
        ),
        migrations.CreateModel(
            name='BlogMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_blog_maker', models.CharField(max_length=200)),
                ('musician_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitar_blog.musician')),
            ],
        ),
    ]
