# Generated by Django 4.0.5 on 2022-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0003_musician_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='cover',
            field=models.ImageField(default=None, upload_to='guitar_blog/images/'),
        ),
    ]
