# Generated by Django 4.0.5 on 2022-07-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0005_alter_musician_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='music',
            field=models.FileField(default=None, upload_to='music/'),
        ),
    ]
