# Generated by Django 4.0.5 on 2022-07-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0006_musician_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
