# Generated by Django 4.0.5 on 2022-07-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0008_remove_musician_music_musiciansongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicianSongs',
            new_name='MusicianSong',
        ),
    ]
