# Generated by Django 4.0.5 on 2022-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0010_alter_musiciansong_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='music',
            field=models.FileField(default=None, upload_to='music/'),
        ),
        migrations.DeleteModel(
            name='MusicianSong',
        ),
    ]
