# Generated by Django 4.0.5 on 2022-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0011_musician_music_delete_musiciansong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='music',
            new_name='music_1',
        ),
        migrations.AddField(
            model_name='musician',
            name='music_2',
            field=models.FileField(default=None, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_3',
            field=models.FileField(default=None, upload_to='music/'),
        ),
    ]
