# Generated by Django 4.0.5 on 2022-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0012_rename_music_musician_music_1_musician_music_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='name_of_blog_maker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='BlogMaker',
        ),
    ]
