# Generated by Django 4.0.5 on 2022-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0013_musician_name_of_blog_maker_delete_blogmaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='music_1_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_2_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_3_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
