# Generated by Django 4.0.5 on 2022-07-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0014_musician_music_1_name_musician_music_2_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='music_1',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='music_1_name',
            new_name='music_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='music_2',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='music_2_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='music_3',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='music_3_name',
        ),
    ]
