# Generated by Django 4.0.5 on 2022-07-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0015_rename_music_1_musician_music_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='music',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='music_name',
        ),
        migrations.CreateModel(
            name='MusicUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(default=None, upload_to='music/')),
                ('music_name', models.CharField(blank=True, max_length=200, null=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitar_blog.musician')),
            ],
        ),
    ]
