# Generated by Django 4.0.5 on 2022-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0017_musician_music_1_musician_music_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='music_1_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_2_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_3_votes',
            field=models.IntegerField(default=0),
        ),
    ]
