# Generated by Django 4.0.5 on 2022-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0021_remove_musician_music_1_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='music_1_votes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_2_votes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='music_3_votes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
