# Generated by Django 4.0.5 on 2022-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0022_musician_music_1_votes_musician_music_2_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='music_1_votes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musician',
            name='music_2_votes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musician',
            name='music_3_votes',
            field=models.BooleanField(default=False),
        ),
    ]
