# Generated by Django 4.0.5 on 2022-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_blog', '0024_musician_music_1_users_musician_music_2_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='music_1_users',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='musician',
            name='music_2_users',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='musician',
            name='music_3_users',
            field=models.JSONField(default=dict),
        ),
    ]
